apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-metrics
  namespace: default
  labels:
    release: prometheus-operator
spec:
  endpoints:
    - port: metrics # Имя порта из вашего Service.
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: scaletestapp  # Этот тег должен совпадать с тегом в вашем Service.      
